spring:
  profiles:
    active: 
    - dev

---

server:
    port: 8201
spring:
    profiles: dev  #开发环境
    application:
        name:  user-config

eureka:
  client:
    register-with-eureka: false  #不把自己注册到注册中心
    fetch-registry: false  # 不拉取服务列表
    service-url:
       defaultZone: http://eureka-dev.com:7001/eureka/

---

server:
    port: 8202
spring:
    profiles: test  #测试环境
    application:
        name:  user-config

eureka:
  client:
    register-with-eureka: false  #不把自己注册到注册中心
    fetch-registry: false  # 不拉取服务列表
    service-url:
       defaultZone: http://eureka-dev.com:7001/eureka/
